### PR TITLE
Adds instructions for installing, uninstalling, updating using Guix

### PR DESCRIPTION
**Pull request by ryanprior**
I packaged the [ProtonVPN linux-cli for Guix](https://guix.gnu.org/packages/protonvpn-cli-2.2.2/) and added instructions for how to install, uninstall and upgrade on Guix to the README. I didn't have examples to follow from other distros (does anybody else package this in their main repo?) so I just kinda interleaved it- please suggest a different approach if you think it could be better organized!

Ryan

### CODE REVIEW

**Comment by Rafficer** [comment]
It's available on Fedora, see #149, but I'm still unsure on how to make the instructions consistent.

**Comment by ryanprior** [comment]
Okay I see what they've done, we could add Guix as another repository. Should I watch how you resolve #149 and then update this PR to build off that?

**Comment by Rafficer** [comment]
That'd be great, yes :)

**Comment by kaplun** [comment]
Hi @ryanprior, thanks a lot for the contribution! Few questions:
* how do you stay up-to-date with our new versions?
* how does it work in terms of trusting with Guix? E.g. in which chain of trust is the user sure that what gets installed is the actual package built from our sources?
* can we amend the current description:

> This is the official command-line interface for ProtonVPN, a secure point-to-point virtual private networking (VPN) service with a gratis tier. It can automatically find and connect to the fastest servers or use Tor over VPN. The gratis tier offers unlimited bandwidth for up to 10 devices.

This has some facts that are not correct. We can come with a more precise paragraph.

**Comment by ryanprior** [comment]
Hi @kaplun!

> how do you stay up-to-date with our new versions?

Guix has a `refresh` tool for maintainers to check the latest version published upstream versus what's in Guix. Here's the output as of today:

```sh-session
$ guix refresh protonvpn-cli
gnu/packages/vpn.scm:319:13: 2.2.2 is already the latest version of protonvpn-cli
```

Apart from checking for your new versions that way, I also subscribe to ProtonVPN updates via email and would be open to any other options/channels.

Guix is a cooperative effort and doesn't have explicit package maintainers, so anyone can initiate an update of the protonvpn-cli package & doesn't have to go through me.

> how does it work in terms of trusting with Guix? E.g. in which chain of trust is the user sure that what gets installed is the actual package built from our sources?

When I initially packaged protonvpn-cli, I cloned this GitHub repo and ran `guix hash` to produce a reproducible digest of the whole repo, sans `.git` folder. That hash is public and [part of the package definition](https://github.com/guix-mirror/guix/blob/master/gnu/packages/vpn.scm#L331).

When Guix builds the package from source it will re-hash the source code and halt with an integrity error unless it has the same hash in the definition. Each time somebody updates the package to a new version, they will also update the hash.

Guix users can opt-in to receive [binary packages](https://guix.gnu.org/manual/en/html_node/On-Trusting-Binaries.html) instead of building everything from source. To do so, they authorize a [substitute server](https://guix.gnu.org/manual/en/html_node/Substitutes.html) which provides pre-built binaries when they're available. These substitutes are signed by the server and checked by the client prior to acceptance.

To provide transparency and accountability, users can [challenge](https://guix.gnu.org/manual/en/html_node/Invoking-guix-challenge.html) the substitute server. Guix builds the challenged package locally and compares it to the substitute, reporting whether they match. Because Guix builds are reproducible, substitutes should always be byte-for-byte identical to the locally built package. For example:

```sh-session
$ guix challenge protonvpn-cli

1 store items were analyzed:
  - 1 (100.0%) were identical
  - 0 (0.0%) differed
  - 0 (0.0%) were inconclusive
```

> can we amend the current description

Absolutely, any errors are mine & will be corrected. Would you like to suggest an improved description paragraph?

**Comment by ryanprior** [comment]
@Rafficer, @kaplun I updated this PR to build off of #149, let me know if you'd like any modifications.

**Comment by ryanprior** [comment]
@Rafficer, @kaplun I updated this PR to build off of #149, let me know if you'd like any modifications.

**Comment by kaplun** [comment]
Looks good to me :+1:

**Pull request merged**
