### PR TITLE
Update utils.py

### PR DESCRIPTION
**Pull request by omidekz**
its an ```PR``` for ```[BUG] issue #97```
i change ```api_domain``` url. its ```hardcode``` and its DANGEROUS, but it works:)

### CODE REVIEW

**Comment by Rafficer** [comment]
I don't see how that fixes something that doesn't work by simply editing the config file.

Also api.protonmail.ch is blocked in Russia, which is why it was initially changed to api.protonvpn.ch.

**Comment by omidekz** [comment]
> I don't see how that fixes something that doesn't work by simply editing the config file.
> 
> Also api.protonmail.ch is blocked in Russia, which is why it was initially changed to api.protonvpn.ch.

```api.protonvpn.ch``` blocked in iran, we can ask for user's country to set true configs

**Comment by Rafficer** [comment]
Users can set the preferred API themselves. How does hardcoding something that is configurable in the first place fix it?

**Comment by calexandru2018** [comment]
Hi @omidekz 

@Rafficer is really gut about this. Users can themselves change this is the configurations, as this solution, as Rafficer pointed out, won't work in other countries.

**Comment by omidekz** [comment]
> Users can set the preferred API themselves. How does hardcoding something that is configurable in the first place fix it?

no, hardcode is bad idea, i just fix it in simpleset way.
i prefer to ask user for which API address to connect or which API is available in their country.

** i accept that this PR is bad and this is just my solution, atleast for iranian users

**Comment by officer47p** [comment]
> > Users can set the preferred API themselves. How does hardcoding something that is configurable in the first place fix it?
> 
> no, hardcode is bad idea, i just fix it in simpleset way.
> i prefer to ask user for which API address to connect or which API is available in their country.
> 
> ** i accept that this PR is bad and this is just my solution, atleast for iranian users

Man thank you a lot, you saved me from buying a NordVPN subscription(which is unnecessarily when proton offers it for free).
A big hug from me.

**Pull request closed without merging**
