### PR TITLE
Run flake8 lint whenever a new PR is made.

### PR DESCRIPTION
**Pull request by calexandru2018**
Added a Github action, so that flake8 linting is triggered whenever a new PR is made.
Also moved github files into appropriate folders.

### CODE REVIEW

**Comment by kaplun** [comment]
Hey @calexandru2018 I am checking in the settings of the repository and it seems I need to setup a self-hosted github runner. Is this the case? Or does GitHub offer cloud runners? (as GitLab)?

**Comment by Rafficer** [comment]
Github offers cloud runners. 2000 Minutes/month are free (depends on the account status, more info on the bottom of [this page](https://github.com/features/actions).)

**Comment by calexandru2018** [comment]
@kaplun as @Rafficer correctly pointed, Github offers cloud runners (as an example this PR has already been run).

**Comment by Rafficer** [comment]
Actually, I seem to have misread the pricing page. It's seems to be only limited to private repos, so we're good and apparently have "unlimited" cloud runners.

**Comment by kaplun** [comment]
Can you fix the failures as part of your PR, so that when we merge we start with a clean slate?

**Comment by Rafficer** [comment]
Let me do this in a different PR :)

**Comment by calexandru2018** [comment]
Should I close this PR then ?

**Comment by Rafficer** [comment]
No, I'd merge it as is. I'll just fix the linting errors that currently come up in a different PR.

**Pull request merged**
